# Generated by Django 4.2.17 on 2024-12-18 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_function', '0001_initial'),
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='jobId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job_function.postedjobs'),
        ),
    ]
